apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  #These labels are related to deployment
  labels:
    component: mysql
    project: expense
    tier: db

spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
      #pod definintion
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0  
        
---
apiVersion: V1
kind: service
metadata:
  name: mysql
  namespace: expense
spec:
selector:
    component: mysql
    project: expense
    tier: db
ports:
  - protocols: TCP  
    port: 3306 #service-port
    targetport: 3306 #target-port